### ISSUE TITLE
Trouble Connecting with iPad

### ISSUE THREAD

**Issue by PCswanson** [ttseng/Spin#1]
The spin is able to be controlled using the Processing sketch. When I plug it into the iPad and run through the setup sequence, it moves the motor a short distance back and forth 4 times and then gives me an "Unable to connect to turntable" error message.

I switched from a Sparkfun Redboard to an actual Arduino Uno, and now it moves a short distance in one direction 4 times (instead of back and forth) and then gives me the same error message.

**Comment by ttseng** [comment]
Are you using the recommended 4-pin 3.5mm audio cable?  

http://www.amazon.com/Supertech%C2%AE3-5mm-Premium-Compatible-Smartphones-computers/dp/B00PLTXJIU/ref=sr_1_1?&ie=UTF8&qid=1438659213&sr=8-1&keywords=3.5mm+4+pole

It needs to be 4 pin (not a standard 3 pin cable).  If you are using a 4-pin cable, please check that the mic lines of both ends are connected.  You can do this with a multimeter (the mic line is the pin closest to the barrel).

Also, please double check when you go into settings on your iPad that under Spin, you allow the app to access the microphone.

Let me know if this resolves the issue!

**Comment by PCswanson** [comment]
I have the recommended cable, and I double checked and the microphone is turned on. Any other suggestions? Thanks!

**Comment by ttseng** [comment]
Did you assemble your own PCB from scratch?  I would double check connections to the MIC line of the audio jack:

![screen shot 2016-03-18 at 12 50 52 pm](https://cloud.githubusercontent.com/assets/519336/13885322/2797b3b0-ed08-11e5-999e-cdbf1ade5e98.png)

Do you mind sharing more information about your device as well (iPad type, OS, etc.)?

**Comment by PCswanson** [comment]
I've tried it on an iPad3 and an iPhone5s. I purchased the PCB and soldered the components - I'm going to check the connections around the mic when I get back to my lab this afternoon. Thanks!

**Comment by PCswanson** [comment]
Here's an update - the problem I started with was solved and I'll blame my own inexperience with surface mount soldering. Specifically the R3 resistor was non functional. I must have done something to it when placing it. I couldn't get a reading at all with a multi tester. Replaced it and I could connect with both the iPad and iPhone. Your suggestion to work back and check from the mic input was very helpful - thanks!

New problem: In case you haven't figured it out, I'm the one you've been tweeting with. The motor doesn't seem to be getting enough power. I've fiddled with the little pot on the motor controller board but it hasn't made a difference. Changing the motor_speed variable from .2 to .1 makes the motor rotate the full 240deg, but now it is out of sync with the app.  Any ideas?  Thanks in advance.

**Comment by ttseng** [comment]
Please ensure that you are using the recommended 12V 600mA power supply: https://www.sparkfun.com/products/9442

It will not have enough power from USB power alone. 

I would also check that the EasyDriver board motor PWR IN pins are getting the expected 12V.

**Comment by PCswanson** [comment]
That was it - I used a 5V supply instead of the 12V one that I purchased for the Spin. It is now fully functional. Thanks!

**Comment by ttseng** [comment]
Great to hear!
